#!/bin/bash
if [ "$1" ]; then
  WORKSPACE=$1
else
  WORKSPACE=`pwd`/projects
fi
docker run -ti --rm \
          -e DISPLAY=$DISPLAY \
          -v /tmp/.X11-unix:/tmp/.X11-unix \
          -v `pwd`/config:/home/developer/config \
          -v $WORKSPACE:/home/developer/IdeaProjects \
          gshiva/idea
