#!/bin/bash

docker run -ti --rm \
           -e DISPLAY=$DISPLAY \
           -v /tmp/.X11-unix:/tmp/.X11-unix \
           -v `pwd`/config:/home/developer/config \
           -v `pwd`/workspace:/home/developer/NetBeansProjects \
           reto/netbeans
