# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1425273148);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1418411770);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1425273028);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1425272907);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 3);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.migration.version", 26);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.rights.3.shown", true);
user_pref("browser.search.countryCode", "US");
user_pref("browser.search.region", "US");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20150224134236");
user_pref("browser.slowStartup.averageTime", 2260);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage_override.buildID", "20150224134236");
user_pref("browser.startup.homepage_override.mstone", "36.0");
user_pref("datareporting.healthreport.lastDataSubmissionRequestedTime", "1425272849361");
user_pref("datareporting.healthreport.lastDataSubmissionSuccessfulTime", "1425272850148");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1425359250148");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1418411710913");
user_pref("datareporting.policy.firstRunTime", "1418411649878");
user_pref("datareporting.sessions.current.activeTicks", 3);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 2077);
user_pref("datareporting.sessions.current.main", 82);
user_pref("datareporting.sessions.current.sessionRestored", 2255);
user_pref("datareporting.sessions.current.startTime", "1425274946690");
user_pref("datareporting.sessions.current.totalTime", 86);
user_pref("datareporting.sessions.currentIndex", 7);
user_pref("datareporting.sessions.previous.5", "{\"s\":1425272785440,\"a\":2,\"t\":398,\"c\":true,\"m\":201,\"fp\":1671,\"sr\":3524}");
user_pref("datareporting.sessions.previous.6", "{\"s\":1425274804829,\"a\":3,\"t\":49,\"c\":true,\"m\":94,\"fp\":2122,\"sr\":2344}");
user_pref("datareporting.sessions.prunedIndex", 4);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("extensions.blocklist.pingCountVersion", -1);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 16);
user_pref("extensions.enabledAddons", "ubufox%40ubuntu.com:3.0,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:36.0");
user_pref("extensions.getAddons.cache.lastUpdate", 1425273148);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.hotfix.lastVersion", "20150225.01");
user_pref("extensions.lastAppVersion", "36.0");
user_pref("extensions.lastPlatformVersion", "36.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.xpiState", "{\"app-global\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"e\":true,\"v\":\"34.0\",\"st\":1425271589000,\"mt\":1424786518000}},\"app-system-share\":{\"ubufox@ubuntu.com\":{\"d\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/ubufox@ubuntu.com\",\"e\":true,\"v\":\"2.9\",\"st\":1425271598000,\"mt\":1420839872000}},\"app-profile\":{\"firefox-hotfix@mozilla.org\":{\"d\":\"/home/developer/.mozilla/firefox/wn1pyub5.default/extensions/firefox-hotfix@mozilla.org.xpi\",\"e\":false,\"v\":\"20150225.01\",\"st\":1425273148000}}}");
user_pref("gecko.buildID", "20150224134236");
user_pref("gecko.mstone", "36.0");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1425272849);
user_pref("media.gmp-gmpopenh264.version", "1.3");
user_pref("media.gmp-manager.lastCheck", 1425272849);
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("places.database.lastMaintenance", 1425272849);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1425274946);
user_pref("toolkit.telemetry.previousBuildID", "20150224134236");
