# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1418411770);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 0);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 3);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.migration.version", 24);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20141127111021");
user_pref("browser.slowStartup.averageTime", 0);
user_pref("browser.slowStartup.samples", 0);
user_pref("browser.startup.homepage_override.buildID", "20141127111021");
user_pref("browser.startup.homepage_override.mstone", "34.0");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1418498049879");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1418411710913");
user_pref("datareporting.policy.firstRunTime", "1418411649878");
user_pref("datareporting.sessions.current.activeTicks", 1);
user_pref("datareporting.sessions.current.firstPaint", 700);
user_pref("datareporting.sessions.current.main", 21);
user_pref("datareporting.sessions.current.sessionRestored", 782);
user_pref("datareporting.sessions.current.startTime", "1418413226664");
user_pref("datareporting.sessions.current.totalTime", 16);
user_pref("datareporting.sessions.currentIndex", 4);
user_pref("datareporting.sessions.previous.0", "{\"s\":1418411649570,\"a\":7,\"t\":206,\"c\":true,\"m\":20,\"fp\":1190,\"sr\":1331}");
user_pref("datareporting.sessions.previous.1", "{\"s\":1418411861712,\"a\":0,\"t\":14,\"c\":true,\"m\":31,\"fp\":724,\"sr\":824}");
user_pref("datareporting.sessions.previous.2", "{\"s\":1418411885640,\"a\":5,\"t\":105,\"c\":true,\"m\":21,\"fp\":785,\"sr\":849}");
user_pref("datareporting.sessions.previous.3", "{\"s\":1418412909998,\"a\":3,\"t\":29,\"c\":false,\"m\":31,\"fp\":697,\"sr\":776}");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 16);
user_pref("extensions.enabledAddons", "ubufox%40ubuntu.com:2.9,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:34.0");
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.installCache", "[{\"name\":\"app-system-share\",\"addons\":{\"ubufox@ubuntu.com\":{\"descriptor\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/ubufox@ubuntu.com\",\"mtime\":1418332209000,\"rdfTime\":1401829706000}}},{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1418332207000,\"rdfTime\":1417088159000}}}]");
user_pref("extensions.lastAppVersion", "34.0");
user_pref("extensions.lastPlatformVersion", "34.0");
user_pref("extensions.pendingOperations", false);
user_pref("gecko.buildID", "20141127111021");
user_pref("gecko.mstone", "34.0");
user_pref("loop.soft_start_ticket_number", 2495851);
user_pref("loop.throttled", false);
user_pref("media.gmp-gmpopenh264.lastUpdate", 1418411712);
user_pref("media.gmp-gmpopenh264.version", "1.1");
user_pref("media.gmp-manager.lastCheck", 1418411712);
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1418413226);
user_pref("toolkit.telemetry.previousBuildID", "20141127111021");
